"""add_car_images_column

Revision ID: 3a0e283e4a28
Revises: e7a4449ea631
Create Date: 2026-07-16 04:09:01.067254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0e283e4a28'
down_revision: Union[str, Sequence[str], None] = 'e7a4449ea631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('images', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'images')
    # ### end Alembic commands ###
