"""Add DamageReport model

Revision ID: 6eaa442cecda
Revises: 93c3293d3c59
Create Date: 2026-07-18 04:52:48.172650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eaa442cecda'
down_revision: Union[str, Sequence[str], None] = '93c3293d3c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('before_image_url', sa.String(), nullable=False),
    sa.Column('after_image_url', sa.String(), nullable=False),
    sa.Column('annotated_image_url', sa.String(), nullable=True),
    sa.Column('condition_score', sa.Integer(), nullable=False),
    sa.Column('total_repair_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('damages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('damage_reports')
    # ### end Alembic commands ###
