"""Add driver and insurance to bookings

Revision ID: 93c3293d3c59
Revises: 3a0e283e4a28
Create Date: 2026-07-18 03:56:05.137871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c3293d3c59'
down_revision: Union[str, Sequence[str], None] = '3a0e283e4a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('with_driver', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('bookings', sa.Column('with_insurance', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'with_insurance')
    op.drop_column('bookings', 'with_driver')
    # ### end Alembic commands ###
