"""create vehicle events table

Revision ID: e7a4449ea631
Revises: c3d4e5f6a7b8
Create Date: 2026-07-12 12:49:45.766676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a4449ea631'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('car_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('UNEXPECTED_MOVEMENT', 'SPEEDING', 'GPS_LOST', 'GEOFENCE_EXIT', 'GEOFENCE_ENTER', 'TRACKER_OFFLINE', 'BATTERY_DISCONNECTED', name='vehicleeventtype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='vehicleeventseverity'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_events_booking_created', 'vehicle_events', ['booking_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_events_booking_id'), 'vehicle_events', ['booking_id'], unique=False)
    op.create_index('ix_vehicle_events_car_created', 'vehicle_events', ['car_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_events_car_id'), 'vehicle_events', ['car_id'], unique=False)
    op.create_index(op.f('ix_vehicle_events_created_at'), 'vehicle_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_events_created_at'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_car_id'), table_name='vehicle_events')
    op.drop_index('ix_vehicle_events_car_created', table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_booking_id'), table_name='vehicle_events')
    op.drop_index('ix_vehicle_events_booking_created', table_name='vehicle_events')
    op.drop_table('vehicle_events')
    # ### end Alembic commands ###
